{% set version = '2.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tswge
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tswge_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tswge/tswge_{{ version }}.tar.gz
  sha256: 7c7533b5a2dcf58d2d58458f010d2a32ca2a9953517e2470497f0b0e840581de

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]

  host:
    - r-base
    - r-mass
    - r-polynomf
    - r-astsa
    - r-dplyr
    - r-forecast
    - r-ggplot2
    - r-magrittr
    - r-nnfor
    - r-plotrix
    - r-signal
    - r-tidyverse
    - r-waveslim
    - r-zoo

  run:
    - r-base
    - r-mass
    - r-polynomf
    - r-astsa
    - r-dplyr
    - r-forecast
    - r-ggplot2
    - r-magrittr
    - r-nnfor
    - r-plotrix
    - r-signal
    - r-tidyverse
    - r-waveslim
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tswge')"           # [not win]
    - "\"%R%\" -e \"library('tswge')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=tswge
  license: GPL-2
  summary: Accompanies the texts Time Series for Data Science with R by Woodward, Sadler and
    Robertson & Applied Time Series Analysis with R, 2nd edition by Woodward, Gray,
    and Elliott.  It is helpful for data analysis and for time series instruction.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: tswge
# Type: Package
# Title: Time Series for Data Science
# Version: 2.1.0
# Date: 2023-1-30
# Author: Wayne Woodward
# Maintainer: Bivin Sadler <bsadler@smu.edu>
# Description: Accompanies the texts Time Series for Data Science with R by Woodward, Sadler and Robertson & Applied Time Series Analysis with R, 2nd edition by Woodward, Gray, and Elliott.  It is helpful for data analysis and for time series instruction.
# Imports: signal,PolynomF,MASS,waveslim,astsa,tidyverse,zoo,plotrix, dplyr, ggplot2, magrittr,nnfor,forecast
# License: GPL-2
# NeedsCompilation: no
# LazyData: TRUE
# Packaged: 2023-01-31 04:15:10 UTC; loaner
# Repository: CRAN
# Date/Publication: 2023-01-31 13:10:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
